version: '3.8'
services:
  db:
    image: mariadb:10.6.16
    container_name: thepi_wp_db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
    ports:
      - '3306:3306'
    networks:
      - wpnet

  wordpress:
    image: wordpress:6.8.1-php8.3-apache
    container_name: thepi_wp_app
    depends_on:
      - db
    volumes:
      - ./:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
      WORDPRESS_DB_NAME: wordpress
    ports:
      - '8080:80'
    networks:
      - wpnet

  wpcli:
    image: wordpress:cli-php8.3
    container_name: thepi_wp_cli
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    entrypoint: ['wp']
    networks:
      - wpnet
    environment:
      - WP_CLI_PHP_ARGS=-d memory_limit=1G

volumes:
  db_data:

networks:
  wpnet:
    driver: bridge
